#!/bin/sh

py_dirs="src tests dev"

echo "Formatting..."
fmt_output=$(ruff format --check --diff $py_dirs)

if [ $? -ne 0 ]; then
    echo "** ERROR: Formatting issues were found. Commit blocked. **"
    echo "$fmt_output"
    exit 1
fi

echo "Linting..."
lint_output=$(ruff check $py_dirs)

if [ $? -ne 0 ]; then
    echo "** ERROR: Linting failed. Commit blocked. **"
    echo "$lint_output"
    exit 1
fi

echo "Running tests..."
pytest

if [ $? -ne 0 ]; then
    echo "** ERROR: Tests failed. Commit blocked. **"
    exit 1
fi

exit 0
